### ISSUE TITLE
TomEE error on startup of speaker-web service (service still seems to run OK)

### ISSUE THREAD

**Issue by karianna** [microprofile/microprofile-conference#103]
Whenever I start the TomEE service:

`java -DadditionalSystemProperties="-Dport.http=9191 -Dport.ajp=9292 -Dport.shutdown=9393" -jar target/microservice-speaker-web-exec.jar`

I get the following error:

```
SEVERE - Failed to start connector [Connector[AJP/1.3-auto-1]]
org.apache.catalina.LifecycleException: Failed to start component [Connector[AJP/1.3-auto-1]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:440)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:791)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:655)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)
Caused by: org.apache.catalina.LifecycleException: The connector cannot start since the specified port value of [-1] is invalid
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1028)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	... 11 more
```

The service does appear to run OK though

**Comment by karianna** [comment]
Fixed.
