### ISSUE TITLE
Unable to build web application due to gulp.js error

### ISSUE THREAD

**Issue by katheris** [microprofile/microprofile-conference#97]
Building the web application I get an unsupported environment error in both Windows and ubuntu:

in ubuntu:
[INFO] Running 'gulp.js build' in /home/kate/git/katheris/microprofile-conference/web-application/src/main/static
[ERROR] /home/kate/git/katheris/microprofile-conference/web-application/src/main/static/node_modules/node-sass/lib/index.js:13
[ERROR]     throw new Error(errors.unsupportedEnvironment());
[ERROR]     ^
[ERROR] 
[ERROR] Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (51)
[ERROR] For more information on which environments are supported please see:
[ERROR] https://github.com/sass/node-sass/releases/tag/v3.10.1
[ERROR]     at Object.<anonymous> (/home/kate/git/katheris/microprofile-conference/web-application/src/main/static/node_modules/node-sass/lib/index.js:13:11)
[ERROR]     at Module._compile (module.js:573:32)
[ERROR]     at Object.Module._extensions..js (module.js:582:10)
[ERROR]     at Module.load (module.js:490:32)
[ERROR]     at tryModuleLoad (module.js:449:12)
[ERROR]     at Function.Module._load (module.js:441:3)
[ERROR]     at Module.require (module.js:500:17)
[ERROR]     at require (internal/module.js:20:19)
[ERROR]     at Object.<anonymous> (/home/kate/git/katheris/microprofile-conference/web-application/src/main/static/node_modules/gulp-sass/index.js:187:21)
[ERROR]     at Module._compile (module.js:573:32)

in windows:
[INFO] --- frontend-maven-plugin:1.0:gulp (gulp-build) @ web-application ---
[INFO] Running 'gulp.js build' in C:\Users\IBM_ADMIN\git\katheris\microprofile-conference\web-application\src\main\static
[ERROR] C:\Users\IBM_ADMIN\git\katheris\microprofile-conference\web-application\src\main\static\node_modules\node-sass\lib\index.js:13
[ERROR]     throw new Error(errors.unsupportedEnvironment());
[ERROR]     ^
[ERROR]
[ERROR] Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (51)
[ERROR] For more information on which environments are supported please see:
[ERROR] https://github.com/sass/node-sass/releases/tag/v3.10.0
[ERROR]     at Object.<anonymous> (C:\Users\IBM_ADMIN\git\katheris\microprofile-conference\web-application\src\main\static\node_modules\node-sass\lib\index.js:13:11)
[ERROR]     at Module._compile (module.js:573:32)
[ERROR]     at Object.Module._extensions..js (module.js:582:10)
[ERROR]     at Module.load (module.js:490:32)
[ERROR]     at tryModuleLoad (module.js:449:12)
[ERROR]     at Function.Module._load (module.js:441:3)
[ERROR]     at Module.require (module.js:500:17)
[ERROR]     at require (internal/module.js:20:19)
[ERROR]     at Object.<anonymous> (C:\Users\IBM_ADMIN\git\katheris\microprofile-conference\web-application\src\main\static\node_modules\gulp-sass\index.js:187:21)
[ERROR]     at Module._compile (module.js:573:32)

**Comment by iainduncani** [comment]
node-sass v3.10.0 isn't supported on Windows with node 7:

https://github.com/sass/node-sass/releases/tag/v3.10.0

I got past this error by adding this to the dependencies in web-application\src\main\static\package.json:

> "node-sass": "^3.11.1"

However, I then just get a further error trying to load the primeng module added by commit 9583eb so I don't know if the fix for node-sass is definitely the right one.

**Comment by iainduncani** [comment]
@katheris I think this is because the mvn clean doesn't clean out the old node_modules directory. I ran this on a fresh clone in a VM and it worked so I went back and tidied out my old node_modules and it now works on my Windows machine as well. I will add something to clean out the node_modules on a mvn clean so that we don't see this on future version updates...
